export const forRent = [
	{
		id: 1,
		price: 10000,
		rentFrequency: 'daily',
		rooms: 1,
		title: 'dubai rent1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'rent',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'rent.jpg',
			},
		],
	},
	{
		id: 2,
		price: 10000,
		rentFrequency: 'daily',
		rooms: 1,
		title: 'dubai rent1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'rent',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'rent.jpg',
			},
		],
	},
	{
		id: 3,
		price: 10000,
		rentFrequency: 'daily',
		rooms: 1,
		title: 'dubai rent1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'rent',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'rent.jpg',
			},
		],
	},
	{
		id: 4,
		price: 10000,
		rentFrequency: 'daily',
		rooms: 1,
		title: 'dubai rent1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'rent',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'rent.jpg',
			},
		],
	},
	{
		id: 5,
		price: 10000,
		rentFrequency: 'daily',
		rooms: 1,
		title: 'dubai rent1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'rent',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'rent.jpg',
			},
		],
	},
	{
		id: 6,
		price: 10000,
		rentFrequency: 'daily',
		rooms: 1,
		title: 'dubai rent1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'rent',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'rent.jpg',
			},
		],
	},
	{
		id: 7,
		price: 10000,
		rentFrequency: 'daily',
		rooms: 1,
		title: 'dubai rent1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'rent',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'rent.jpg',
			},
		],
	},
	{
		id: 8,
		price: 10000,
		rentFrequency: 'daily',
		rooms: 1,
		title: 'dubai rent1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'rent',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'rent.jpg',
			},
		],
	},
]
export const forSale = [
	{
		id: 1,
		price: 10000,

		rooms: 1,
		title: 'dubai buy1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'buy',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'buy.jpg',
			},
		],
	},
	{
		id: 2,
		price: 10000,

		rooms: 1,
		title: 'dubai buy1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'buy',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'buy.jpg',
			},
		],
	},
	{
		id: 3,
		price: 10000,

		rooms: 1,
		title: 'dubai buy1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'buy',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'buy.jpg',
			},
		],
	},
	{
		id: 4,
		price: 10000,

		rooms: 1,
		title: 'dubai buy1',
		baths: 1,
		area: 200,
		agency: 'agency',
		isVerified: true,
		description: 'jhgfd jkghfsd jhsfd jhfd lhjhfdsjh kljdf',
		type: 'kjsdf',
		purpose: 'buy',
		furnishingStatus: 'true',
		amenities: 'hjsdfjkhdfjhdfsjhsdfj',
		photos: [
			{
				id: 1,
				src: 'buy.jpg',
			},
		],
	},
]
